name: Expo Publish on Production
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_CLI_TOKEN }}
          expo-cache: true
      - run: expo build:android
      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          msg: Apk is generated successfully!, you can [download from here](https://expo.io/@numanarshad.dev/projects/ReactNativeDemo).