name: Expo Publish on Staging
on: [pull_request]
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_CLI_TOKEN }}
          expo-cache: true
      - run: npm install
      - run: expo install
      - run: expo publish --release-channel staging
      - uses: unsplash/comment-on-pr@master
        with:
          msg: Expo publish is ready for review, you can [see it here](https://expo.io/@numanarshad.dev/projects/ReactNativeDemo).