name: Expo Publish
on: [pull_request]
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_CLI_TOKEN }}
          expo-cache: true
      - run: npm install
      - run: expo install
      - run: expo publish --release-channel=pr-${{ github.event.number }}
      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          msg: Expo publish is ready for review, you can [see it here](https://expo.io/@numanarshad.dev/use-expo?release-channel=pr-${{ github.event.number }}).